# Generated by Django 3.0.2 on 2020-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameportal', '0002_auto_20200420_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=1000)),
                ('game_id', models.IntegerField()),
            ],
        ),
    ]
