# Generated by Django 3.0.2 on 2020-05-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameportal', '0003_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
